### ISSUE TITLE
Sorry garouflex 

### ISSUE THREAD

**Issue by Dhiraj8780** [HorizonUnix/UXTU4Unix#16]
I know I'm fking annoying u while doing this 

But can u please unban me 
I'm not Yasser not any type of coder 
Please unban me I wanna use that bot 
Please 🥺🥺🙏🙏

**Comment by gorouflex** [comment]
Stop spamming me everywhere man, I do not receive your appeal.

**Comment by Dhiraj8780** [comment]
Bro I'm not a spammer
But I'm banded for no reason 
Can u just unban me 🥺🥺🥺

**Comment by Dhiraj8780** [comment]
And why no appeal 
I didn't did anything wrong...

**Comment by Dhiraj8780** [comment]
Please at least talk to me

**Comment by Dhiraj8780** [comment]
Please on discord 
Or over here

**Comment by gorouflex** [comment]
> Please on discord Or over here

Whatsoever but I NEVER waste my time just to hear your complain. That’s all, you will be banned on our org project.

**Comment by Dhiraj8780** [comment]
I know how precious time is 
And I respect you and your work As well as your time.....

Thanks for co-operative nature 
All I want was just a unban from server as there is no valid particular reason 

Your project is WAY TO OP
If u ever feel I was innocent unban me....

**Comment by Dhiraj8780** [comment]
> > Please on discord Or over here
> 
> Whatsoever but I NEVER waste my time just to hear your complain. That’s all, you wi



> > Please on discord Or over here
> 
> Whatsoever but I NEVER waste my time just to hear your complain. That’s all, you will be banned on our org project.


Man why are u so strict 
Can u just unban me

**Comment by Dhiraj8780** [comment]
It means I'm not banded
